include: package:very_good_analysis/analysis_options.2.3.0.yaml
linter:
  rules:
    sort_pub_dependencies: true
    public_member_api_docs: false
    exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.chopper.dart"
    - "**/*.config.dart"
    - "**/*.gr.dart"
