name: quiz_android
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  cloud_firestore: ^3.1.14
  dartz: ^0.10.1
  dio: ^4.0.6
  firebase_auth: ^3.3.14
  firebase_core: ^1.14.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  font_awesome_flutter: ^9.2.0
  freezed_annotation: ^1.1.0
  google_fonts: ^2.3.1
  intl: ^0.17.0
  json_annotation: ^4.4.0
  objectbox: ^1.4.1
  objectbox_flutter_libs: any

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.6
  objectbox_generator: any
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
